version: '3.3'

services:
  effective_service:
    build: ./
    depends_on:
      - "pg_db"
    environment:
      - POSTGRES_HOST=pg_db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=effectivedb
      - IS_DEBUG=true
    ports:
      - "3000:3000"
    
  pg_db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=effectivedb
    volumes:
      - ./.data_base/postgres/data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"